export const mockDestinationData = [
  // Accommodations
  {
    id: "acc1",
    type: "accommodation",
    title: "Rainforest Eco Lodge",
    description: "Sustainable treehouse accommodation powered by solar energy with stunning views of the rainforest.",
    location: "Monteverde",
    price: 120,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["solar-powered", "rainwater-harvesting", "farm-to-table", "locally-owned"],
    sustainabilityScore: 92,
    carbonSaved: 32,
    natureImpact: 75,
    communityImpact: 45,
  },
  {
    id: "acc2",
    type: "accommodation",
    title: "Eco Beach Cabanas",
    description: "Off-grid beach cabanas constructed with sustainable materials and powered by renewable energy.",
    location: "Manuel Antonio",
    price: 95,
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["energy-efficient", "plastic-free", "locally-owned", "renewable-energy"],
    sustainabilityScore: 88,
    carbonSaved: 28,
    natureImpact: 65,
    communityImpact: 50,
  },
  {
    id: "acc3",
    type: "accommodation",
    title: "Mountain View Eco Hotel",
    description: "LEED-certified hotel with panoramic mountain views, organic gardens, and zero-waste practices.",
    location: "San José",
    price: 150,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["eco-certified", "zero-waste", "organic", "renewable-energy"],
    sustainabilityScore: 90,
    carbonSaved: 35,
    natureImpact: 70,
    communityImpact: 40,
  },

  // Activities
  {
    id: "act1",
    type: "activity",
    title: "Guided Forest Hike",
    description: "Explore the local ecosystem with knowledgeable guides on a leave-no-trace hiking adventure.",
    location: "Monteverde Cloud Forest",
    price: 85,
    rating: 4.8,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["leave-no-trace", "local-guides", "wildlife-protection"],
    sustainabilityScore: 95,
    carbonSaved: 15,
    natureImpact: 85,
    communityImpact: 40,
  },
  {
    id: "act2",
    type: "activity",
    title: "Sustainable Coffee Tour",
    description: "Visit a sustainable coffee plantation and learn about eco-friendly farming practices.",
    location: "Central Valley",
    price: 65,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["organic", "locally-owned", "community-support"],
    sustainabilityScore: 93,
    carbonSaved: 12,
    natureImpact: 80,
    communityImpact: 60,
  },
  {
    id: "act3",
    type: "activity",
    title: "Wildlife Sanctuary Visit",
    description:
      "Support wildlife conservation efforts by visiting this sanctuary for rescued and rehabilitated animals.",
    location: "La Fortuna",
    price: 75,
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["wildlife-protection", "conservation", "education"],
    sustainabilityScore: 91,
    carbonSaved: 10,
    natureImpact: 90,
    communityImpact: 35,
  },

  // Restaurants
  {
    id: "res1",
    type: "restaurant",
    title: "Farm-to-Table Restaurant",
    description: "Local, organic cuisine sourced from farms within 30 miles. Zero-waste kitchen practices.",
    location: "San José",
    price: 35,
    rating: 4.9,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["locally-sourced", "organic", "zero-waste", "seasonal"],
    sustainabilityScore: 94,
    carbonSaved: 18,
    natureImpact: 70,
    communityImpact: 55,
  },
  {
    id: "res2",
    type: "restaurant",
    title: "Vegetarian Rainforest Café",
    description: "Plant-based cuisine using organic, locally grown ingredients with a zero-waste approach.",
    location: "Monteverde",
    price: 28,
    rating: 4.6,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["plant-based", "organic", "zero-waste", "locally-sourced"],
    sustainabilityScore: 96,
    carbonSaved: 22,
    natureImpact: 80,
    communityImpact: 45,
  },

  // Transportation
  {
    id: "tra1",
    type: "transportation",
    title: "Electric Vehicle Rental",
    description: "Zero-emission electric vehicle rental to explore the local area with minimal environmental impact.",
    location: "San José",
    price: 65,
    rating: 4.7,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["electric-vehicles", "carbon-offset", "renewable-energy"],
    sustainabilityScore: 90,
    carbonSaved: 45,
    natureImpact: 60,
    communityImpact: 20,
  },
  {
    id: "tra2",
    type: "transportation",
    title: "Eco-Friendly Shuttle Service",
    description: "Shared shuttle service using fuel-efficient vehicles and carbon offset programs.",
    location: "Nationwide",
    price: 40,
    rating: 4.5,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["carbon-offset", "shared-transport", "fuel-efficient"],
    sustainabilityScore: 85,
    carbonSaved: 30,
    natureImpact: 50,
    communityImpact: 25,
  },

  // Flights
  {
    id: "fli1",
    type: "flight",
    title: "Carbon Offset Flight",
    description: "Direct flight with automatic carbon offsetting included in your ticket price.",
    location: "San José International Airport",
    price: 450,
    rating: 4.5,
    image: "/placeholder.svg?height=200&width=200",
    sustainabilityFeatures: ["carbon-offset", "direct-flights", "eco-friendly-airlines"],
    sustainabilityScore: 75,
    carbonSaved: 85,
    natureImpact: 40,
    communityImpact: 15,
  },
]
